apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: sample-app
        service: webapp
    spec:
      containers:
        - name: webapp
          image: acrfuri102.azurecr.io/webapp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2368
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:2368
            - name: WebApiBaseAddress
              value: http://webapi